ALTER TABLE auto_responses ADD COLUMN is_bold BOOLEAN DEFAULT FALSE;
ALTER TABLE auto_responses ADD COLUMN is_italic BOOLEAN DEFAULT FALSE;
ALTER TABLE auto_responses ADD COLUMN is_underline BOOLEAN DEFAULT FALSE;
